Repository 2023-Winter-techeer-Bootcamp-Team-E/frontend, pull requests merged in 2024-01, with the labels that each got.

#4 [Design/#1] 오른쪽 스티커창 구현 완료
  src/components/RightSticker.jsx
  src/pages/StartPage.jsx
Labels: 🎨Design

#5 test
  src/App.jsx
  src/components/NavigateBar.jsx
Labels: 🎨Design

#7 [Design/#6] 라우팅 설정 + 파일 삭제
  src/App.css
  src/App.jsx
  src/pages/MainPage.jsx
Labels: 📚Chore

#10 [Design/#9] 오른쪽 스티커창 퍼블리싱 완료
  public/img/Cloud1.png
  public/img/Cloud2.png
  src/components/RightSticker.jsx
Labels: 🎨Design

#12 [Design/#3] 기본 스티커창 구현 완료
  public/img/Sun.png
  src/components/BasicSticker.jsx
Labels: 🎨Design

#15 [Design/#14] 기본 스티커창 + 스크롤 버튼 구현 완료
  public/img/downbutton.png
  public/img/upbutton.png
  src/components/BasicStickerScroll.jsx
Labels: 🎨Design

#17 design : 스몰, 라지 스케치북 퍼블리싱
  public/img/HaruConnectingBook.png
  public/img/LargeSpring.png
  public/img/Logo_HaruConnecting.png
  public/img/SmallSpring.png
  src/components/LargeSketchbook.jsx
  src/components/SmallSketchbook.jsx
Labels: 🎨Design

#20 design: 로그인 창 구현 완료
  src/components/LoginBar.jsx
Labels: 🎨Design

#19 design:로그인및 회원가입 버튼 퍼블리싱, book이미지 수정
  public/img/HaruConnectingBook.png
  src/components/SignIn_Up.jsx
Labels: 🎨Design

#23 [design/#21]: 시작 페이지 구현 완료
  public/img/StartBookImg.png
  src/App.jsx
  src/components/StartButton.jsx
  src/pages/StartPage.jsx
Labels: 🎨Design

#25 [design/#24] 게스트 로그인 모달 창 구현 완료
  public/img/Logo_Shadow.png
  src/App.jsx
  src/assets/Fonts/BMJUA.ttf
  src/assets/Fonts/fonts.css
  src/components/BasicSticker.jsx
  src/components/CheckButton.jsx
  src/components/GuestModal.jsx
  src/components/GuestPwInput.jsx
Labels: 🎨Design

#26 [Design/#22] 로그인 및 회원가입 페이지 구현 등 완료
  src/App.jsx
  src/components/LoginInput.jsx
  src/components/SignIn_Up.jsx
  src/components/SmallSketchbook.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
  src/pages/StartPage.jsx
Labels: 🎨Design

#29 [desing/#27] 메인 페이지 퍼블리싱 완료
  src/App.jsx
  src/components/BasicSticker.jsx
  src/components/LargeSketchbook.jsx
  src/components/MainPage/sample.jsx
  src/components/NavigateBar.jsx
  src/components/RightSticker.jsx
  src/pages/MainPage.jsx
  src/pages/StartPage.jsx
Labels: 🎨Design

#33 [Chore/#32] 폴더구조 변경 + 폰트적용 + 파일 이름 변경
  src/App.jsx
  src/assets/Fonts/fonts.css
  src/assets/img/Cloud1.png
  src/assets/img/Cloud2.png
  src/assets/img/HaruConnectingBook.png
  src/assets/img/LargeSpring.png
  src/assets/img/Logo_HaruConnecting.png
  src/assets/img/Logo_Shadow.png
  src/assets/img/NavigateBar_arrow.png
  src/assets/img/NavigateBar_bell.png
  src/assets/img/SmallSpring.png
  src/assets/img/StartBookImg.png
  src/assets/img/Sun.png
  src/assets/img/downbutton.png
  src/assets/img/upbutton.png
  src/components/BasicSticker.jsx
  src/components/GuestModal/CheckButton.jsx
  src/components/GuestModal/GuestModal.jsx
  src/components/GuestModal/GuestPwInput.jsx
  src/components/LargeSketchbook.jsx
  src/components/NavigateBar.jsx
  src/components/RightSticker.jsx
  src/components/SmallSketchbook.jsx
  src/components/Start/StartButton.jsx
  src/index.css
  src/pages/CalendarPage.jsx
  src/pages/LoginPage.jsx
  src/pages/SignUpPage.jsx
  src/pages/StartPage.jsx
Labels: 📚Chore

#35 [design/#28] 인원 다 찼을때 나오는 모달 창 구현 완료
  src/assets/img/SadLogo.png
  src/assets/img/homebutton.png
  src/components/BasicSticker.jsx
  src/components/GuestFullmodal/FullModal.jsx
  src/components/GuestFullmodal/HomeButton.jsx
  src/components/LargeSketchbook.jsx
Labels: 🎨Design

#39 Design/#36 시작 페이지 + 컴포넌트 크기/단위 수정 완료
  src/assets/Fonts/SEOLLEIMcool.ttf
  src/assets/img/Book.png
  src/assets/img/EmptyLogo.png
  src/assets/img/Papers.png
  src/components/BasicSticker.jsx
  src/components/GuestFullmodal/FullModal.jsx
  src/components/GuestFullmodal/HomeButton.jsx
  src/components/GuestModal/GuestModal.jsx
  src/components/LargeSketchbook.jsx
  src/components/RightSticker.jsx
  src/components/Start/StartButton.jsx
  src/index.css
  src/pages/CalendarPage.jsx
  src/pages/StartPage.jsx
Labels: 🎨Design

#50 [Design/#49] 시작 페이지 애니메이션 기능 퍼블리싱 완료
  src/assets/img/Book.png
  src/assets/img/Book2.png
  src/assets/img/Papers.png
  src/assets/img/Papers2.png
  src/components/CalendarPage/Calender.jsx
  src/pages/StartPage.jsx
Labels: 🎨Design

#52 [Design/#51] 배경 그라데이션 추가 완료
  src/pages/CalendarPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/LoginPage.jsx
  src/pages/SignUpPage.jsx
  src/pages/StartPage.jsx
Labels: 🎨Design

#54 [Design/#48] 회원가입 페이지 입력 오류 애니메이션 구현
  index.html
  package.json
  src/assets/img/MaskingTape1.png
  src/assets/img/MaskingTape2.png
  src/assets/img/WebIcon.png
  src/components/CalendarPage/Calender.jsx
  src/components/CalendarPage/DateNotification.jsx
  src/components/CalendarPage/RightSticker/SelectInnerPaper.jsx
  src/components/CalendarPage/RightSticker/ShareLink.jsx
  src/components/RightSticker.jsx
  src/components/SignIn_Up.jsx
  src/pages/CalendarPage.jsx
  src/pages/LoginPage.jsx
  src/pages/SignUpPage.jsx
  yarn.lock
Labels: 🎨Design

#56 [Design/#42] 반응형 구현 완료
  index.html
  src/App.jsx
  src/GlobalStyles.js
  src/components/ MinScreenWarning.jsx
  src/index.css
Labels: 🎨Design

#66 [Fix/#61] 새로고침했을때 이미지 보이는 현상 해결 + 반응형 이후 작아졌던 컴포넌트 사이즈 키움 + y스크롤 hidden
  index.html
  src/GlobalStyles.js
  src/assets/img/ScreenWarning.png
  src/components/CalendarPage/DateNotification.jsx
  src/components/LargeSketchbook.jsx
  src/components/SmallSketchbook.jsx
  src/index.css
  src/pages/CalendarPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/LoginPage.jsx
  src/pages/SignUpPage.jsx
  src/pages/StartPage.jsx
Labels: 🎨Design, ❤️‍🔥BugFix

#67 [feat/#65] 회원가입 아이디 중복 확인
  src/pages/SignUpPage.jsx
Labels: ✨Feat

#70 [feat/#68] 일기작성, api 경로 변경 [중간완성]
  src/api/config.js
  src/components/CalendarPage/DateNotification.jsx
  src/components/OpenDiary.jsx
  src/pages/LoginPage.jsx
  vite.config.js
Labels: ✨Feat

#73 [Feat/#72] 캘린더 조회 API 연동 완료
  src/assets/img/Calendar/DiaryEditIcon.png
  src/components/CalendarPage/Calendar.css
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/DateNotification.jsx
  src/components/NavigateBar.jsx
  src/pages/LoginPage.jsx
Labels: ✨Feat

#75 [Feat/#74] 기본 스티커(Static Sticker) API GET 연동 완료
  src/components/BasicSticker.jsx
  src/components/CalendarPage/Calendar.jsx
Labels: ✨Feat

#79 [feat/#71] https에서 일기작성
  src/components/CalendarPage/DateNotification.jsx
Labels: ✨Feat

#84 [Feat/#80] 작성중인 일기에서 링크생성
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/DateNotification.jsx
  src/pages/CalendarPage.jsx
Labels: ✨Feat

#85 [Feat/#81] 배경지 불러오는 api 호출 (중간점검)
  src/assets/img/InnerImg/DiaryInnerPaintingDog.png
  src/assets/img/InnerImg/DiaryinnerPaintingInfo.png
  src/assets/img/InnerImg/MainInnerimg5.png
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/DateNotification.jsx
  src/pages/CalendarPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/LoginPage.jsx
  yarn.lock
Labels: ✨Feat

#89 [Feat/#83] 스티커 드래그 안되는 문제 + 닫기버튼, 텍스트박스 닫기버튼 커서 포인터로만 뜨게 수정
  src/components/DiaryPage/TextBox.jsx
  src/components/Stickers.jsx
  src/pages/DiaryPage.jsx
Labels: ✨Feat

#91 [Feat/#90] 스티커 드래그 범위 조정 + BasicSticker 겹치는 현상 해결
  src/components/DiaryPage/InnerImg.jsx
  src/components/DiaryPage/TextBox.jsx
  src/components/Stickers.jsx
  src/pages/DiaryPage.jsx
Labels: ✨Feat

#93 [Feat/#78] userInfoStore 상태관리 설정 완료
  package.json
  src/components/CalendarPage/ProfileMenu.jsx
  src/components/LoginInput.jsx
  src/components/NavigateBar.jsx
  src/pages/CalendarPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/LoginPage.jsx
  src/store/UserInfoStore.jsx
  yarn.lock
Labels: ✨Feat

#96 [fix/#95] 수정 완료
  src/components/NavigateBar.jsx
Labels: ❤️‍🔥BugFix

#99 [Feat/#86] DateNotification 컴포넌트 분해 후 상태관리 설정
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/Case1.jsx
  src/components/CalendarPage/Case2.jsx
  src/components/CalendarPage/Case3.jsx
  src/components/CalendarPage/DateNotification.jsx
  src/pages/CalendarPage.jsx
  src/store/useDateNotificationStore.js
  src/store/useDiaryURL.js
  yarn.lock
Labels: ✨Feat

#105 [Fix/#101] Calendar 각종 버그 수정(미완)
  src/assets/img/InnerImg/SelectInnerImg5.png
  src/components/CalendarPage/Calendar.css
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/Case1.jsx
  src/components/CalendarPage/Case2.jsx
  src/components/CalendarPage/Case3.jsx
  src/components/CalendarPage/DateNotification.css
  src/components/CalendarPage/DateNotification.jsx
  src/pages/CalendarPage.jsx
  src/store/useSelectDateInfoStore.js
Labels: ❤️‍🔥BugFix

#107 [Feat/#103] 일기 최종 저장 api 연동 (임시)
  src/components/DiaryPage/DHomeButton.jsx
  src/components/DiaryPage/SaveButton.jsx
Labels: ✨Feat

#108 [Fix/#106] Calendar 각종 버그 수정
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/Case2.jsx
  src/components/CalendarPage/Case3.jsx
  src/store/useIconUpdate.js
Labels: ❤️‍🔥BugFix

#110 [Feat/#104] 과거 기록 조회 api 연동 완료
  src/App.jsx
  src/components/CalendarPage/Calendar.jsx
  src/components/DiaryPage/DHomeButton.jsx
  src/components/DiaryPage/InnerImg.jsx
  src/components/OpenDiary.jsx
  src/pages/PastPage.jsx
Labels: ✨Feat

#112 [Feat/#109] DALL-E 스티커 API 연동 완료
  src/GlobalStyles.js
  src/assets/Fonts/Crown_Mychew.ttf
  src/assets/img/InnerImg/DiaryInnerPaintingInfo.png
  src/components/CalendarPage/Case1.jsx
  src/components/CalendarPage/Case2.jsx
  src/components/CalendarPage/Case3.jsx
  src/components/CalendarPage/RightSticker/SelectInnerPaper.jsx
  src/components/CalendarPage/RightSticker/ShareLink.jsx
  src/components/DiaryPage/InnerImg.jsx
  src/components/DiaryPage/RightSticker.jsx
  src/components/DiaryPage/TextBox.jsx
  src/components/GuestModal/GuestPwInput.jsx
  src/components/LargeSketchbook.jsx
  src/components/LoginInput.jsx
  src/components/NavigateBar.jsx
  src/components/SignIn_Up.jsx
  src/components/SmallSketchbook.jsx
  src/components/Start/StartButton.jsx
  src/index.css
  src/pages/CalendarPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/LoginPage.jsx
  src/pages/SignUpPage.jsx
  src/store/UserInfoStore.jsx
  src/store/useDateNotificationStore.js
  src/store/useDiaryContent.js
  src/store/useDiaryURL.js
  src/store/useIconUpdate.js
  src/store/useInnerPage.js
  src/store/useSelectDateInfoStore.js
Labels: ✨Feat

#114 [Feat/#113] 달력의 기본 스티커, 텍스트박스 드래그드롭, 크기조절, 회전 라이브러리 적용 성공
  src/components/CalendarPage/Calendar.css
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/DateNotification.jsx
  src/components/CalendarPage/NotificationMenu.jsx
  src/components/DiaryPage/RightSticker.jsx
  src/components/SignIn_Up.jsx
  src/components/Stickers.jsx
  src/pages/CalendarPage.jsx
Labels: ✨Feat

#118 [Feat/#92] 웹소켓 구현 완료
  src/api/config.js
  src/components/BasicSticker.jsx
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/Case2.jsx
  src/components/CalendarPage/Case3.jsx
  src/components/CalendarPage/DateNotification.jsx
  src/components/CalendarPage/ProfileMenu.jsx
  src/components/DiaryPage/DalleSticker.jsx
  src/components/DiaryPage/InnerImg.jsx
  src/components/DiaryPage/RightSticker.jsx
  src/components/DiaryPage/Stickers.jsx
  src/components/DiaryPage/TextBox.jsx
  src/components/DiaryPage/TextButton.jsx
  src/components/NavigateBar.jsx
  src/components/Stickers.jsx
  src/pages/CalendarPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/LoginPage.jsx
  src/pages/PastPage.jsx
  src/pages/SignUpPage.jsx
  src/stores/dalleStore.js
  src/stores/stickerStore.js
  src/stores/textStore.js
  src/stores/useDateNotificationStore.js
  src/stores/useDiaryContent.js
  src/stores/useDiaryURL.js
  src/stores/useIconUpdate.js
  src/stores/useInnerPage.js
  src/stores/useSelectDateInfoStore.js
  src/stores/userInfoStore.js
  vite.config.js
  yarn.lock
Labels: ✨Feat

#121 [Design/#117] UI 피드백 반영 완료
  src/assets/img/Calendar/preBtn.png
  src/assets/img/Calendar/preBtn2.png
  src/assets/img/InnerImg/MainInnerImg4.png
  src/assets/img/InnerImg/MainInnerImg5.png
  src/assets/img/InnerImg/MainInnerImg6.png
  src/assets/img/InnerImg/SelectInnerImg4.png
  src/assets/img/InnerImg/SelectInnerImg5.png
  src/assets/img/InnerImg/SelectInnerImg6.png
  src/assets/img/diaryBubble.png
  src/assets/img/diaryLogo.png
  src/components/BasicSticker.jsx
  src/components/CalendarPage/Calendar.css
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/Case1.jsx
  src/components/CalendarPage/Case2.jsx
  src/components/CalendarPage/Case3.jsx
  src/components/CalendarPage/DateNotification.jsx
  src/components/DiaryPage/DHomeButton.jsx
  src/components/DiaryPage/RightSticker.jsx
  src/components/DiaryPage/SaveButton.jsx
  src/components/DiaryPage/TextBox.jsx
  src/components/DiaryPage/TextButton.jsx
  src/components/LargeSketchbook.jsx
  src/pages/CalendarPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/PastPage.jsx
Labels: 🎨Design

#123 [Feat/#120] 동적인 URL 생성 및 공유
  src/App.jsx
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/Case2.jsx
  src/components/CalendarPage/Case3.jsx
  src/components/DiaryPage/InnerImg.jsx
  src/components/LargeSketchbook.jsx
  src/components/NavigateBar.jsx
  src/pages/CalendarPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/LoginPage.jsx
Labels: ✨Feat

#125 [Feat/#119] 웹소켓 한글 입력 오류 IME 입력기 적용
  src/assets/img/xclose.png
  src/components/DiaryPage/DalleSticker.jsx
  src/components/DiaryPage/Stickers.jsx
  src/components/DiaryPage/TextBox.jsx
  src/pages/DiaryPage.jsx
Labels: 🎨Design, ✨Feat

#127 [Feat/#126] 웹소켓 url diaryId 연동
  src/components/CalendarPage/Case2.jsx
  src/components/DiaryPage/InnerImg.jsx
  src/components/DiaryPage/RightSticker.jsx
  src/pages/DiaryPage.jsx
  src/stores/diaryIdStore.js
Labels: ✨Feat

#129 [Feat/#124] 일기 DallE 스티커 디자인 수정 및 lottie적용
  package.json
  src/assets/img/DiaryTutorial.png
  src/assets/lottie/LottieAirplaneAnimation.json
  src/assets/lottie/LottieDrawingAnimation.json
  src/assets/lottie/LottieRunAnimation.json
  src/components/DiaryPage/InnerImg.jsx
  src/components/DiaryPage/RightSticker.jsx
  src/components/DiaryPage/TextBox.jsx
  src/pages/DiaryPage.jsx
  yarn.lock
Labels: 🎨Design, ✨Feat

#130 [Feat/#115] 달력 스티커 부착 기능 API 연동 (미완)
  src/components/CalendarPage/Calendar.jsx
  src/components/CalendarPage/CalendarStickers.jsx
  src/components/DiaryPage/InnerImg.jsx
  src/pages/CalendarPage.jsx
Labels: ✨Feat
