Repository 2023-Winter-techeer-Bootcamp-Team-E/frontend, pull requests merged in 2024-02, with the labels that each got.

#135 [Fix/#134] 배경 이미지 불러오는데 문제 수정
  src/components/DiaryPage/InnerImg.jsx
Labels: ❤️‍🔥BugFix

#137 [Design/#136] : guest UI 수정
  src/components/DiaryPage/InnerImg.jsx
  src/components/NavigateBar.jsx
  src/pages/DiaryPage.jsx
Labels: 🎨Design, ✨Feat

#139 [Design/#136] 비밀번호 숨기기/보이기 버튼 제작 + 튜토리얼 버튼 삭제 + a
  src/GlobalStyles.js
  src/assets/img/Calendar/CopyURL.png
  src/assets/img/CloseEye.png
  src/assets/img/LargeSpring.png
  src/assets/img/NavigateBar_bell.png
  src/assets/img/OpenEye.png
  src/assets/img/SmallSpring.png
  src/assets/lottie/LottieAirplaneAnimation.json
  src/assets/lottie/LottieDrawingAnimation.json
  src/components/CalendarPage/Case2.jsx
  src/components/CalendarPage/Case3.jsx
  src/components/CalendarPage/ProfileMenu.jsx
  src/components/DiaryPage/RightSticker.jsx
  src/components/LoginInputTypePW.jsx
  src/pages/CalendarPage.jsx
Labels: 🎨Design

#141 [Feat/#128] 웹소켓 내용 최종저장 버튼에 데이터 전달
  src/components/DiaryPage/DHomeButton.jsx
  src/components/DiaryPage/InnerImg.jsx
  src/components/DiaryPage/SaveButton.jsx
  src/components/DiaryPage/Stickers.jsx
  src/pages/DiaryPage.jsx
  src/pages/PastPage.jsx
Labels: 🎨Design, ✨Feat

#144 [Feat/#143] 링크 썸네일 및 설명 메타태그 구현
  index.html
  src/pages/DiaryPage.jsx
  src/pages/StartPage.jsx
Labels: ✨Feat
